# fly.toml file generated for vibe-spam-redis on 2022-03-28T01:23:01-05:00
# https://fly.io/docs/reference/redis/

app = "vibe-spam-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  destination = "/data"
  source = "vibe_spam_redis_server"
